ls:
  .dir: regex:\d{4}-([a-zA-Z0-9]+-)*[a-zA-Z0-9]+ | regex:(baekjoon|programmers)
  baekjoon/*:
    .dir: regex:\d{4}-([a-zA-Z0-9가-힣]+-)*[a-zA-Z0-9가-힣]+
  programmers/*:
    .dir: regex:.+

  .cs: regex:[a-zA-Z0-9]+\.[a-zA-z]+
    
ignore:
  - .git
  - .github
  - .idea
  - README.md
