ls:
  .dir: regex:\d{4}-([a-zA-Z0-9]+-)*[a-zA-Z0-9]+ | regex:(baekjoon|programmers)
  baekjoon/*:
    .dir: regex:\d{4}-([a-zA-Z0-9가-힣]+-)*[a-zA-Z0-9가-힣]+
  programmers/*:
    .dir: regex:.+
  
  .js: regex:[^\s]+\.js
  .ts: regex:[^\s]+\.ts
  .py: regex:[^\s]+\.py
  .cs: regex:[^\s]+\.cs
  .cpp: regex:[^\s]+\.cpp
  .java: regex:[^\s]+\.java
  .go: regex:[^\s]+\.go

ignore:
  - .git
  - .github
  - .idea
  - README.md
